### PR TITLE
Removed unnecessary code

### PR DESCRIPTION
**Pull request by HoodieRocks**
ur not funny guys :(

### CODE REVIEW

**Comment by TheZoidMaster** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by Silabear** [comment]
Hell nah

**Comment by Silabear** [comment]
@HoodieRocks those functions are v important

**Comment by TheZoidMaster** [comment]
they are definitely necessary for library function

**Comment by JaegerwaldDev** [comment]
ughfajushdjuashdk fine

**Pull request merged**
